[package]
name = "ggml-quants"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "GGML quantization implementations"

[dependencies]
ggml-core = { path = "../ggml-core" }
anyhow.workspace = true
half.workspace = true
