[package]
name = "llama-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line interface for llama-rs"

[dependencies]
llama-core = { path = "../../crates/llama/llama-core" }
anyhow.workspace = true
clap.workspace = true
